backend/models/Kpi.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "kpi".
 *
 * @property integer $id
 * @property string $name
 * @property integer $year
 * @property string $target
 * @property string $base_unit
 * @property string $polarization
 * @property string $period_type
 * @property integer $is_excluded
 * @property integer $is_active
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property User $createdBy
 * @property User $updatedBy
 * @property KpiFile[] $kpiFiles
 * @property KpiScore[] $kpiScores
 */
class Kpi extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            \yii\behaviors\TimestampBehavior::className(),
            \yii\behaviors\BlameableBehavior::className(),
        ];
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kpi';
    }

    public static function isExcluded($id = '') {
        switch ($id) {
            case '0'    : return 'No'; break;
            case '1'    : return 'Yes'; break;
            case 'all'  : return ['0' => 'No', '1' => 'Yes']; break;
            default     : return; break;
        }
    }

    public static function isActive($id = '') {
        switch ($id) {
            case '0'    : return 'No'; break;
            case '1'    : return 'Yes'; break;
            case 'all'  : return ['1' => 'Yes', '0' => 'No']; break;
            default     : return; break;
        }
    }

    public static function polarization($id = '') {
        switch ($id) {
            case 'Min'    : return 'Min'; break;
            case 'Max'    : return 'Max'; break;
            case 'all'  : return ['Min' => 'Min', 'Max' => 'Max']; break;
            default     : return; break;
        }
    }

    public static function periodType($id = '') {
        switch ($id) {
            case '1'    : return 'Monthly'; break;
            case '3'    : return 'Quarterly'; break;
            case '12'    : return 'Annually'; break;
            case 'all'  : return ['1' => 'Monthly', '3' => 'Quarterly', '12' => 'Annually']; break;            
            default     : return; break;
        }
    }

    public static function generate() {
        $current_year = date('Y');
        $max_existed_year = Kpi::find()->max('year');
        Kpi::deleteAll(['year' => $current_year]);
        if ($max_existed_year) {
            $old_models = Kpi::findAll(['year' => $max_existed_year]);
            foreach ($old_models as $old_model) {
                $new_model = new Kpi();
                $new_model->name            = $old_model->name;
                $new_model->year            = $current_year;
                $new_model->target          = $old_model->target;
                $new_model->base_unit       = $old_model->base_unit;
                $new_model->polarization    = $old_model->polarization;
                $new_model->period_type     = $old_model->period_type;
                $new_model->is_excluded     = $old_model->is_excluded;
                $new_model->is_active       = $old_model->is_active;
                $new_model->save();
            }
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'year'], 'required'],
            [['year', 'is_excluded', 'is_active', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['name', 'target', 'base_unit', 'polarization', 'period_type'], 'string', 'max' => 191],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'year' => 'Year',
            'target' => 'Target',
            'base_unit' => 'Base Unit',
            'polarization' => 'Polarization',
            'period_type' => 'Period Type',
            'is_excluded' => 'Is Excluded',
            'is_active' => 'Is Active',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKpiFiles()
    {
        return $this->hasMany(KpiFile::className(), ['kpi_id' => 'id'])->orderBy(['date' => SORT_DESC]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKpiScores()
    {
        return $this->hasMany(KpiScore::className(), ['kpi_id' => 'id'])->orderBy(['month' => SORT_ASC]);
    }
}

backend/controllers/KpiController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\KpiFile;
use backend\models\KpiScore;
use backend\models\KpiFileSearch;
use backend\models\KpiScoreSearch;
use backend\models\Kpi;
use backend\models\KpiSearch;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\IntegrityException;
use yii\data\ActiveDataProvider;

/**
 * KpiController implements the CRUD actions for Kpi model.
 */
class KpiController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'delete-score' => ['POST'],
                    'delete-file' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Kpi models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new KpiSearch();
        $queryParams = Yii::$app->request->queryParams;
        if (!isset($queryParams['KpiSearch'])) $queryParams['KpiSearch'] = array();
        if (!isset($queryParams['KpiSearch']['year'])) $queryParams['KpiSearch']['year'] = date('Y');
        $dataProvider = $searchModel->search($queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionReport()
    {
        $get = Yii::$app->request->get();
        $year = (isset($get['year']) && $get['year']) ? $get['year'] : date('Y');

        if (Kpi::findOne(['year' => $year]) === null) {
            Kpi::generate();
        }

        return $this->render('kpi', [
            'year' => $year,
        ]);
    }

    /**
     * Displays a single Kpi model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        
        $dataProviderFile = new ActiveDataProvider(['query' => KpiFile::find()->where(['kpi_id' => $id])->orderBy('id desc')]);
        $dataProviderScore = new ActiveDataProvider(['query' => KpiScore::find()->where(['kpi_id' => $id])->orderBy('id desc')]);

        $dataProviderFile->pagination = false;
        $dataProviderScore->pagination = false;

        $modelFile = new KpiFile();
        $modelScore = new KpiScore();

        $modelFile->kpi_id = $id;
        $modelScore->kpi_id = $id;

        $is_redirected = 0;

        if ($post = Yii::$app->request->post()) {
            if ($modelFile->load($post)) {
                $modelFile->pdfFile = UploadedFile::getInstance($modelFile, 'pdfFile');
                $modelFile->excelFile = UploadedFile::getInstance($modelFile, 'excelFile');
                
                if ($modelFile->save()) {
                    // print "<pre>"; print_r($modelFile); die();
                    if ($modelFile->pdfFile) {
                        $modelFile->pdf = $modelFile->tableName().'/'.$modelFile->id.'.'.$modelFile->pdfFile->extension;
                    }
                    if ($modelFile->excelFile) {
                        $modelFile->excel = $modelFile->tableName().'/'.$modelFile->id.'.'.$modelFile->excelFile->extension;
                    }
                    if ($modelFile->save()) {
                        if ($modelFile->pdfFile) $modelFile->pdfFile->saveAs(Yii::$app->params['uploadLocation'].$modelFile->pdf);
                        if ($modelFile->excelFile) $modelFile->excelFile->saveAs(Yii::$app->params['uploadLocation'].$modelFile->excel);
                    } else {
                        Yii::$app->session->addFlash('warning', 'Failed to save file.');
                    }
                    $is_redirected = 1;
                }
            }
            if ($modelScore->load($post)) {
                if ($modelScore->save()) { $is_redirected = 1; }
            }
        }

        if ($is_redirected) {
            return $this->redirect(['view', 'id' => $id]);
        }

        return $this->render('view', [
            'model' => $model,
            'modelFile' => $modelFile,
            'modelScore' => $modelScore,
            'dataProviderFile' => $dataProviderFile,
            'dataProviderScore' => $dataProviderScore,
        ]);
    }

    /**
     * Displays a single Kpi model.
     * @param integer $id
     * @return mixed
     */
    public function actionViewReadonly($id)
    {
        $model = $this->findModel($id);
        
        $dataProviderFile = new ActiveDataProvider(['query' => KpiFile::find()->where(['kpi_id' => $id])->orderBy('id desc')]);
        $dataProviderScore = new ActiveDataProvider(['query' => KpiScore::find()->where(['kpi_id' => $id])->orderBy('id desc')]);

        $dataProviderFile->pagination = false;
        $dataProviderScore->pagination = false;

        return $this->render('view-readonly', [
            'model' => $model,
            'dataProviderFile' => $dataProviderFile,
            'dataProviderScore' => $dataProviderScore,
        ]);
    }

    /**
     * Creates a new Kpi model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Kpi();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Kpi model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Kpi model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        try {
            $model = $this->findModel($id);
            KpiScore::deleteAll(['kpi_id' => $id]);
            foreach ($model->kpiFiles as $kpiFile) {
                $excelFile = Yii::getAlias('@uploads/'.$kpiFile->excel);
                $pdfFile = Yii::getAlias('@uploads/'.$kpiFile->pdf);
                if (file_exists($excelFile) && is_file($excelFile)) unlink($excelFile);
                if (file_exists($pdfFile) && is_file($pdfFile)) unlink($pdfFile);
                unlink(Yii::getAlias('@uploads/'.$kpiFile->pdf));
            }
            KpiFile::deleteAll(['kpi_id' => $id]);
            $model->delete();
            return $this->redirect(['index']);
        } catch (IntegrityException $e) {
            throw new \yii\web\HttpException(500,"Integrity Constraint Violation. This data can not be deleted due to the relation.", 405);
        }
    }

    public function actionDeleteScore($id)
    {
        try {
            $model = KpiScore::findOne($id);
            $model->delete();
            return $this->redirect(['view', 'id' => $model->kpi_id]);
        } catch (IntegrityException $e) {
            throw new \yii\web\HttpException(500,"Integrity Constraint Violation. This data can not be deleted due to the relation.", 405);
        }
    }

    public function actionDeleteFile($id)
    {
        try {
            $model = KpiFile::findOne($id);
            $excelFile = Yii::getAlias('@uploads/'.$model->excel);
            $pdfFile = Yii::getAlias('@uploads/'.$model->pdf);
            if (file_exists($excelFile) && is_file($excelFile)) unlink($excelFile);
            if (file_exists($pdfFile) && is_file($pdfFile)) unlink($pdfFile);
            $model->delete();
            return $this->redirect(['view', 'id' => $model->kpi_id]);
        } catch (IntegrityException $e) {
            throw new \yii\web\HttpException(500,"Integrity Constraint Violation. This data can not be deleted due to the relation.", 405);
        }
    }

    /**
     * Finds the Kpi model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Kpi the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Kpi::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    public function actionDownload($id, $filename) 
    {
        $model = KpiFile::findOne($id);
        $filepath = Yii::getAlias('@uploads/'.$filename);
        $extension = '.'.substr($filename, strpos($filename, ".") + 1);
        if (file_exists($filepath)) Yii::$app->response->sendFile($filepath, $model->kpi->name.' '.$model->date.$extension, ['inline'=>true]);
    }

    public function actionRemove($id, $filename) 
    {
        $filepath = Yii::getAlias('@uploads/'.$filename);
        if (file_exists($filepath)) {
            unlink($filepath);
        }
        return $this->redirect(['view', 'id' => $id]);
    }
}

backend/views/kpi/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Kpi */

$this->title = Yii::t('app', 'Create KPI');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'KPI'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="kpi-create box-- box---success">
	<div class="box---header"></div>

    <div class="box---body">
	    <?= $this->render('_form', [
	        'model' => $model,
	    ]) ?>
    </div>

</div>

backend/views/kpi/kpi.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use kartik\grid\GridView;
use kartik\export\ExportMenu;
use backend\models\Kpi;
use backend\models\KpiFile;
use backend\models\KpiScore;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\KpiSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

// Yii::$app->params['showTitle'] = false;
// $this->title = \backend\models\Config::findOne(['name' => 'Dashboard Title'])->value;
$this->title = 'KPI';

$kpis = Kpi::find()->select(['*', '(select count(kpi_score.id) from kpi_score where kpi_id = kpi.id) as count_score'])
    ->where(['kpi.is_excluded' => '0', /* 'is_active' => '1', */ 'kpi.year' => $year])->groupBy('kpi.id')->orderBy('count_score DESC, name ASC')->all();
$kpiExcludeds = Kpi::findAll(['is_excluded' => 1, /* 'is_active' => '1', */ 'year' => $year]);

$years = Kpi::find()->groupBy('year')->all();
?>

<!-- <h1 style="font-size:24px;margin:0; margin-bottom:15px">
    <?= Html::encode($this->title) ?>
    <?= Html::dropDownList('year', $year, ArrayHelper::map($years, 'year', 'year'), ['id' => 'year', 'class' => 'form-control year-selector', 'placeholder' => 'year...', 'style' => 'border-color: #00acd6; font-size: 16px; padding: 2px 8px; margin-top: -5px;']) ?>
</h1> -->

<!-- <div class="visible-xs" style="width:150px;">
    <?= Html::dropDownList('year', $year, ArrayHelper::map($years, 'year', 'year'), ['id' => 'year', 'class' => 'form-control year-selector', 'placeholder' => 'year...', 'style' => 'border-color: #00acd6; font-size: 16px; padding: 2px 8px; margin-top: -5px;']) ?>
    <p></p>
</div> -->

<!-- <div class="box box-primary box-body"> -->
<div class="row">

    <?php if ($kpiExcludeds) { ?> <div class="col-md-12"> <?php } else { ?> <div class="col-md-12"> <?php } ?>
        <div class="box box-primary box-body">

            <table style="width:100%;margin-bottom:5px;">
                <tr>
                    <td style="padding:2px">
                        <?= Html::dropDownList('year', $year, ArrayHelper::map($years, 'year', 'year'), ['id' => 'year', 'class' => 'form-control year-selector', 'placeholder' => 'year...', 'style' => 'width: 150px; border-color: #00acd6; font-size: 16px; padding: 2px 8px; margin-top: -5px;']) ?>
                    </td>
                    <td style="padding:2px" class="text-right">
                        <?= Html::a('<i class="fa fa-gear"></i> Setting', ['/kpi/index'], ['class' => 'btn btn-default', 'style' => 'margin-right:5px']) ?>
                        <?php // echo Html::a('<i class="fa fa-th-list"></i> View Monitoring (Non KPI)', ['/site/index-excluded'], ['class' => 'btn btn-info']) ?>
                    </td>
                </tr>
            </table>

            <div style="width:100%; overflow-y:auto;">
            <table class="table table-bordered table-striped" style="margin-bottom:0;">
            <tr style="background:#0d5884; color:#eee">
                <th style="background:none; border-left-color:#0d5884; vertical-align:middle" rowspan="2" colspan="2" class="text-center"><big><big>K P I</big></big></th>
                <th style="background:none; border-right-color:#0d5884;" colspan="12" class="text-center">Aktual <?= date('Y') ?></th>
            </tr>
            <tr style="background:#0d5884; color:#eee">
                <?php for ($i = 1; $i <= 12; $i++) { 
                    $border_right_color = $i == 12 ? "#0d5884" : "#ddd";
                ?>
                   <!-- <th style="background:none; font-family:monospace; width:1px; white-space:nowrap"><?= str_pad($i, 2, "0", STR_PAD_LEFT); ?></th> -->
                   <th style="background:none; font-family:monospace; width:1px; white-space:nowrap; border-right-color: <?= $border_right_color ?>"><?= date('M', mktime(0, 0, 0, $i, 10)) ?></th>
                <?php } ?>                
            </tr>
            <?php foreach ($kpis as $kpi) { ?>
                <tr>
                    <td style="width:1px; white-space:nowrap; border-right: none">
                        <?= Html::a('<i class="fa fa-calendar text-info"></i>', ['/kpi/view-readonly', 'id' => $kpi->id], ['class' => 'btn btn-default btn-xs']) ?>
                        <?= $kpi->kpiFiles && $kpi->kpiFiles[0]->excel ? Html::a('<i class="fa fa-file-excel-o text-success"></i>', ['/kpi/download', 'id' => $kpi->kpiFiles[0]->id, 'filename' => $kpi->kpiFiles[0]->excel], ['class' => 'btn btn-flat btn-default btn-xs']) : '' ?>
                    </td>
                    <td style="border-left: none; border-right: none">
                        <?= $kpi->kpiFiles && $kpi->kpiFiles[0]->pdf ? Html::a($kpi->name, ['/kpi/download', 'id' => $kpi->kpiFiles[0]->id, 'filename' => $kpi->kpiFiles[0]->pdf]) : $kpi->name ?>
                        <small class="text-muted">
                        <small class="text-muted">
                        <br>
                        <!-- Target:  --><b><?= $kpi->target ? Yii::$app->formatter->asDecimal($kpi->target, 0) : '-' ?></b> <?= $kpi->target ? $kpi->base_unit : ''; ?>
                        | <!-- Polarisasi:  --><b><?= $kpi->polarization ? $kpi->polarization : '-'; ?></b>
                        | <!-- Periode:  --><b><?= $kpi->period_type ? $kpi::periodType($kpi->period_type) : '-'; ?></b>
                        </small>
                        </small>
                    </td>
                    <?php for ($i = 1; $i <= 12; $i++) { 
                        $kpiScore = KpiScore::findOne(['kpi_id' => $kpi->id, 'month' => $i]);
                        $actual = $kpiScore ? $kpiScore->value : null;
                        $background = '';
                        if ($actual) {
                            //if ($actual == $kpi->target) $background = 'yellow';
                            if ($actual == $kpi->target) $background = 'yellow';
                            if ($kpi->polarization == "Max") {
                                if ($actual >= $kpi->target) $background = '#a6e22e';
                                if ($actual < $kpi->target) $background = '#f85b93';
                            }
                            if ($kpi->polarization == "Min") {
                                if ($actual > $kpi->target) $background = '#f85b93';
                                if ($actual <= $kpi->target) $background = '#a6e22e';
                            }
                        }
                        if (!$kpi->is_active) $background = "#aaa";
						$actual_disp = ctype_digit($actual) ? Yii::$app->formatter->asDecimal($actual, 0) : $actual;
                    ?>
                        <td style="background:<?= $background ?>; text-align:center; font-weight:bold; font-family:monospace; border-left:1px solid #ddd; border-right:1px solid #ddd;"><?= $actual_disp ?></td>
                    <?php } ?>
                </tr>
            <?php } ?>
            </table>
            </div>
        </div>
    </div>

    <?php if ($kpiExcludeds) { ?>
    <div class="col-md-12" style="">
        <table class="table table-hover" style="border:1px solid #ddd; background:#fff">
        <?php foreach ($kpiExcludeds as $kpiExcluded) { ?>
            <tr>
                <td style="border-top:1px solid #ddd; width:1px; white-space:nowrap">
                    <?= Html::a('<i class="fa fa-calendar text-info"></i>', ['/kpi/view-readonly', 'id' => $kpiExcluded->id], ['class' => 'btn btn-default btn-xs']) ?>
                    <?= $kpiExcluded->kpiFiles && $kpiExcluded->kpiFiles[0]->excel ? Html::a('<i class="fa fa-file-excel-o text-success"></i>', ['/kpi/download', 'id' => $kpiExcluded->kpiFiles[0]->id, 'filename' => $kpiExcluded->kpiFiles[0]->excel], ['class' => 'btn btn-flat btn-default btn-xs']) : '' ?>
                </td>
                <td style="border-top:1px solid #ddd;"><?= $kpiExcluded->kpiFiles && $kpiExcluded->kpiFiles[0]->pdf ? Html::a($kpiExcluded->name, ['/kpi/download', 'id' => $kpiExcluded->kpiFiles[0]->id, 'filename' => $kpiExcluded->kpiFiles[0]->pdf]) : $kpiExcluded->name ?></td>
            </tr>
        <?php } ?>
        </table>
    </div>
    <?php } ?>

</div>

<!-- </div> -->

<?php 
    $this->registerJs('
        $(".year-selector").change(function() {
            year = $(this).val();
            window.location = "'.Url::base().'?r=site/index&year="+year;
        });
    ', \yii\web\View::POS_READY);
?>

backend/views/kpi/view-readonly.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;
use kartik\grid\GridView;
use backend\models\KpiScore;

/* @var $this yii\web\View */
/* @var $model backend\models\Kpi */

$this->title = $model->name;
// $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'KPI'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-md-6">

        <div class="kpi-view box-- box---info">

            <div class="box---body">
                <p>
                <?= Html::a('<i class="glyphicon glyphicon-pencil"></i> '. Yii::t('app', 'Update'), ['view', 'id' => $model->id], [
                    'class' => 'btn btn-warning',
                ]) ?>
                </p>

                <?= DetailView::widget([
                    'options' => ['class' => 'table detail-view'],
                    'model' => $model,
                    'attributes' => [
                        // 'id',
                        'name',
                        'year',
                        'target',
                        'base_unit',
                        'polarization',
                        'period_type',
                        // 'is_excluded:integer',
                        // 'is_active:integer',
                        // 'created_at:datetime',
                        // 'updated_at:datetime',
                        // 'createdBy.username:text:Created By',
                        // 'updatedBy.username:text:Updated By',
                    ],
                ]) ?>
            </div>
        </div>
    </div>



    <div class="col-md-3">
        <div class="box-- box---info">
            <div class="box---header">
                <div class="box---title">File</div>
            </div>
            <div class="box---body">
                <?= GridView::widget([
                    'dataProvider' => $dataProviderFile,
                    // 'pjax' => true,
                    'hover' => true,
                    'striped' => false,
                    'bordered' => false,
                    'panel' => false,
                    'summary' => false,
                    'pjaxSettings' => ['options' => ['id' => 'gridFile']],
                    'columns' => [
                        'date:date:Document Date',
                        [
                            'header' => 'Excel',
                            'format'=> 'html',
                            'value' => function($data) {
                                return ($data->excel ? Html::a('<i class="fa fa-file-excel-o text-success"></i>', ['/kpi/download', 'id' => $data->id, 'filename' => $data->excel], ['class' => 'btn btn-flat btn-default btn-xs', 'data-pjax' => 0]) : '');
                            },
                            'headerOptions' => ['style' => 'width:1px; text-align:right; white-space:nowrap'],
                            'contentOptions' => ['style' => 'width:1px; text-align:right; white-space:nowrap'],
                        ],
                        [
                            'header' => 'PDF',
                            'format'=> 'html',
                            'value' => function($data) {
                                return ($data->pdf ? Html::a('<i class="fa fa-file-pdf-o text-danger"></i>', ['/kpi/download', 'id' => $data->id, 'filename' => $data->pdf], ['class' => 'btn btn-flat btn-default btn-xs', 'data-pjax' => 0]) : '');
                            },
                            'headerOptions' => ['style' => 'width:1px; text-align:right; white-space:nowrap'],
                            'contentOptions' => ['style' => 'width:1px; text-align:right; white-space:nowrap'],
                        ],
                    ],
                ]); ?>
            </div>
        </div>
    </div>
    
    <?php if (!$model->is_excluded) { ?>
    <div class="col-md-3">
        <div class="box-- box---info">
            <div class="box---header">
                <div class="box---title">Realisasi</div>
            </div>
            <div class="box---body">
                <?= GridView::widget([
                    'dataProvider' => $dataProviderScore,
                    // 'pjax' => true,
                    'hover' => true,
                    'striped' => false,
                    'bordered' => false,
                    'panel' => false,
                    'summary' => false,
                    'pjaxSettings' => ['options' => ['id' => 'gridScore']],
                    'columns' => [
                        [
                            'attribute' => 'month',
                            'value' => function($data) { return KpiScore::month($data->month); }
                        ],
                        [
                            'attribute' => 'value',
                            'headerOptions' => ['style' => 'width:1px; text-align:right'],
                            'contentOptions' => ['style' => 'width:1px; text-align:right'],
                        ],
                    ],
                ]); ?>
            </div>
        </div>
    </div>
    <?php } ?>

</div>